# Development Profile
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.com.marketplace=DEBUG
logging.level.org.springframework.web=DEBUG

# application-dev.properties sert à mettre des réglages spécifiques au mode développement
# (ex: afficher les requêtes SQL, logs plus détaillés).
