# ==========================================
# BASE CONFIGURATION (tous les profils)
# ==========================================
spring.application.name=sa7-marketplace
server.port=8080

# Profil actif par défaut
spring.profiles.active=dev

# JPA - pas de création automatique (chaque profil gère ça)
spring.jpa.open-in-view=false

# Logging base
logging.level.root=INFO
logging.level.com.marketplace=DEBUG
